<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Cg\Cms\Content\HtmlToTiptap;
use DOMDocument;
use DOMElement;
use DOMNode;
use DOMXPath;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

/**
 * Rebuild the live site's content from its built HTML, for development.
 *
 * The Astro site's last build (dist/client) is the only complete record of
 * what the live pages contain that exists on this machine: the old database
 * is on the server, and the scripts that built most pages never covered the
 * home page. This reads that HTML and writes a fixture LiveBuildSeeder loads,
 * so local pages carry real copy and can be compared with the live build.
 *
 * Block-built pages are reconstructed by recognising each Astro block's
 * markup. Anything that matches no known block is reported, never dropped
 * silently. The Phase 6 import reads the real database and does not use this.
 */
final class ExtractBuildCommand extends Command
{
    protected $signature = 'site:extract-build
        {dist=/Users/chris/dev/chrisgarlick/dist/client : The built Astro site}
        {--output=database/seeders/fixtures/live-build.json : Where to write the fixture}';

    protected $description = 'Extract the live site\'s content from its built HTML into a seeder fixture';

    /** slug => [file, title]. Titles are the navigation labels; the built HTML only carries SEO titles. */
    private const PAGES = [
        'home' => ['index.html', 'Home'],
        'about' => ['about/index.html', 'About'],
        'contact' => ['contact/index.html', 'Contact'],
        'services' => ['services/index.html', 'Services'],
        'ai-implementation' => ['services/ai-implementation/index.html', 'AI Implementation'],
        'workflow-automation' => ['services/workflow-automation/index.html', 'Workflow Automation'],
        'ai-agents' => ['services/ai-agents/index.html', 'Custom AI Agents'],
        'data-extraction' => ['services/data-extraction/index.html', 'Data Extraction'],
        'ai-engineering' => ['services/ai-engineering/index.html', 'AI Engineering'],
        'industries' => ['industries/index.html', 'Industries'],
        'ai-for-law-firms' => ['industries/ai-for-law-firms/index.html', 'AI for Law Firms'],
        'ai-for-accountancy-firms' => ['industries/ai-for-accountancy-firms/index.html', 'AI for Accountancy Firms'],
        'ai-for-agencies' => ['industries/ai-for-agencies/index.html', 'AI for Agencies'],
    ];

    /** @var array<int, string> */
    private array $unidentified = [];

    /** @var array<int, string> */
    private array $metrics = [];

    public function __construct(private readonly HtmlToTiptap $converter)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $dist = rtrim((string) $this->argument('dist'), '/');

        if (! is_file($dist.'/index.html')) {
            $this->components->error("No built site at {$dist}.");

            return self::FAILURE;
        }

        $fixture = [
            'source' => $dist,
            'note' => 'Generated by site:extract-build. The build carries no publication dates, so dates are derived from listing order, newest first, a week apart.',
            'pages' => $this->pages($dist),
            'case_studies' => $this->caseStudies($dist),
            'articles' => $this->articles($dist),
            'tools' => $this->tools($dist),
            'resources' => $this->resources($dist),
            'proof_metrics' => $this->metrics,
        ];

        $path = base_path((string) $this->option('output'));

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        file_put_contents($path, json_encode($fixture, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)."\n");

        foreach (['pages', 'case_studies', 'articles', 'tools', 'resources', 'proof_metrics'] as $key) {
            $this->components->twoColumnDetail($key, (string) count($fixture[$key]));
        }

        foreach ($fixture['pages'] as $page) {
            $this->components->twoColumnDetail('  '.$page['slug'], implode(', ', array_column($page['blocks'], 'type')));
        }

        if ($this->unidentified !== []) {
            $this->newLine();
            $this->components->warn('Not recognised, left out:');

            foreach ($this->unidentified as $line) {
                $this->line('  '.$line);
            }
        }

        $this->components->info('Wrote '.$this->option('output'));

        return self::SUCCESS;
    }

    /** @return array<int, array<string, mixed>> */
    private function pages(string $dist): array
    {
        $pages = [];

        foreach (self::PAGES as $slug => [$file, $title]) {
            if (! is_file("{$dist}/{$file}")) {
                $this->unidentified[] = "page {$slug}: {$file} missing";

                continue;
            }

            [$xpath, $main] = $this->load("{$dist}/{$file}");

            $pages[] = [
                'slug' => $slug,
                'title' => $title,
                'seo' => $this->seo($xpath),
                'blocks' => $this->blocks($xpath, $main, $slug),
            ];
        }

        return $pages;
    }

    /** @return array<int, array<string, mixed>> */
    private function blocks(DOMXPath $xpath, DOMElement $main, string $slug): array
    {
        $blocks = [];

        foreach ($main->childNodes as $node) {
            // Scripts and styles are behaviour, not content.
            if (! $node instanceof DOMElement || in_array($node->nodeName, ['script', 'style', 'noscript', 'template'], true)) {
                continue;
            }

            // The proof strip's screen-reader list sits beside its section.
            if ($node->nodeName === 'div' && $this->hasClass($node, 'sr-only')) {
                foreach ($xpath->query('.//p', $node) ?: [] as $p) {
                    $text = $this->text($p);

                    if ($text !== '' && ! in_array($text, $this->metrics, true)) {
                        $this->metrics[] = $text;
                    }
                }

                continue;
            }

            $block = $this->block($xpath, $node);

            if ($block === null) {
                $this->unidentified[] = "page {$slug}: <{$node->nodeName} class=\"".$node->getAttribute('class').'">';

                continue;
            }

            $block['data']['theme'] = $node->getAttribute('data-theme') ?: 'light';
            $blocks[] = $block;
        }

        return $blocks;
    }

    /** @return array{type: string, data: array<string, mixed>}|null */
    private function block(DOMXPath $xpath, DOMElement $section): ?array
    {
        $class = ' '.$section->getAttribute('class').' ';

        return match (true) {
            str_contains($class, ' overflow-hidden ') && str_contains($class, ' pt-14 ') => $this->hero($xpath, $section),
            $this->find($xpath, $section, 'marquee-track') !== null => ['type' => 'proof-strip', 'data' => ['metrics' => implode("\n", $this->marquee($xpath, $section))]],
            $this->find($xpath, $section, 'cms-form-container') !== null => ['type' => 'contact-form', 'data' => ['form_slug' => 'contact']],
            $this->find($xpath, $section, 'columns-card') !== null => $this->columns($xpath, $section),
            $xpath->query('.//div[contains(@class, "relative overflow-hidden border")]', $section)?->length > 0 => $this->offerCards($xpath, $section),
            $xpath->query('.//a[contains(@class, "card-hover")][starts-with(@href, "/work/")]', $section)?->length > 0 => $this->caseStudyGrid($xpath, $section),
            $xpath->query('.//div[contains(@class, "divide-y")]//a[starts-with(@href, "/article/")]', $section)?->length > 0 => $this->blogPreview($xpath, $section),
            $xpath->query('.//div[contains(@class, "border-l-2") and contains(@class, "border-accent")]', $section)?->length > 0 => $this->toolsTeaser($xpath, $section),
            str_contains($class, ' bg-bg-primary ') => $this->cta($xpath, $section),
            str_contains($class, ' py-16 ') => ['type' => 'rich-text', 'data' => ['body' => $this->prose($xpath, $section)]],
            str_contains($class, ' py-20 ') => $this->textSection($xpath, $section),
            default => null,
        };
    }

    /** @return array{type: string, data: array<string, mixed>} */
    private function hero(DOMXPath $xpath, DOMElement $section): array
    {
        $data = [
            'label' => $this->firstText($xpath, $section, './/p[contains(@class, "text-accent")][following-sibling::h1]'),
            'heading' => $this->firstText($xpath, $section, './/h1'),
            'subtext' => $this->firstText($xpath, $section, './/h1/following-sibling::p'),
        ];

        foreach ($xpath->query('.//div[contains(@class, "mt-10")]/a', $section) ?: [] as $a) {
            $prefix = $this->hasClass($a, 'bg-accent') ? 'cta' : 'cta_secondary';
            $data["{$prefix}_label"] = $this->text($a);
            $data["{$prefix}_url"] = $a->getAttribute('href');
        }

        return ['type' => 'hero', 'data' => array_filter($data, fn ($v) => $v !== '')];
    }

    /** @return array{type: string, data: array<string, mixed>} */
    private function textSection(DOMXPath $xpath, DOMElement $section): array
    {
        $data = [
            'label' => $this->label($xpath, $section),
            'heading' => $this->firstText($xpath, $section, './/h2'),
        ];

        $prose = $this->find($xpath, $section, 'prose-custom');

        if ($prose !== null) {
            $data['body'] = $this->converter->convert($this->innerHtml($prose));
        }

        $cta = $xpath->query('.//a[contains(@class, "mt-8")]', $section)?->item(0);

        if ($cta instanceof DOMElement) {
            $data['cta_label'] = trim(rtrim($this->text($cta), '→'));
            $data['cta_url'] = $cta->getAttribute('href');
        }

        return ['type' => 'text-section', 'data' => array_filter($data, fn ($v) => $v !== '')];
    }

    /** @return array{type: string, data: array<string, mixed>} */
    private function columns(DOMXPath $xpath, DOMElement $section): array
    {
        $data = [
            'label' => $this->label($xpath, $section),
            'heading' => $this->firstText($xpath, $section, './/h2'),
        ];

        $n = 0;

        foreach ($xpath->query('.//*[contains(concat(" ", normalize-space(@class), " "), " columns-card ")]', $section) ?: [] as $card) {
            if (! $card instanceof DOMElement || ++$n > 4) {
                continue;
            }

            $data["column{$n}_heading"] = $this->firstText($xpath, $card, './/h3');
            $data["column{$n}_body"] = $this->firstText($xpath, $card, './/p');

            if ($card->nodeName === 'a') {
                $data["column{$n}_url"] = $card->getAttribute('href');
                $data["column{$n}_cta_label"] = trim(rtrim($this->firstText($xpath, $card, './span[last()]'), '→'));
            }

            if ($card->getAttribute('data-service-card') !== '') {
                $data["column{$n}_tint"] = $card->getAttribute('data-service-card');
            }
        }

        return ['type' => 'columns', 'data' => array_filter($data, fn ($v) => $v !== '')];
    }

    /**
     * Offer cards. The live block never renders a card's name, only its
     * price, but filters out cards without one; the price stands in for it.
     *
     * @return array{type: string, data: array<string, mixed>}
     */
    private function offerCards(DOMXPath $xpath, DOMElement $section): array
    {
        $data = [];
        $n = 0;

        foreach ($xpath->query('.//div[contains(@class, "relative overflow-hidden border")]', $section) ?: [] as $card) {
            if (++$n > 2) {
                break;
            }

            $price = $this->firstText($xpath, $card, './/p[contains(@class, "font-display")]');
            $data["card{$n}_label"] = $this->firstText($xpath, $card, './span');
            $data["card{$n}_name"] = $price;
            $data["card{$n}_price"] = $price;
            $data["card{$n}_duration"] = $this->firstText($xpath, $card, './/p[contains(@class, "mt-1")]');

            $features = [];

            foreach ($xpath->query('.//li', $card) ?: [] as $li) {
                $features[] = $this->text($li);
            }

            $data["card{$n}_features"] = implode("\n", $features);
        }

        return ['type' => 'offer-cards', 'data' => array_filter($data, fn ($v) => $v !== '')];
    }

    /** @return array{type: string, data: array<string, mixed>} */
    private function caseStudyGrid(DOMXPath $xpath, DOMElement $section): array
    {
        $intro = $xpath->query('.//div[contains(@class, "mb-12")]/p', $section);

        return ['type' => 'case-study-grid', 'data' => array_filter([
            'heading' => $intro?->item(0) ? $this->text($intro->item(0)) : '',
            'subtext' => $intro?->item(1) ? $this->text($intro->item(1)) : '',
            'limit' => $xpath->query('.//a[contains(@class, "card-hover")]', $section)?->length ?: 4,
        ], fn ($v) => $v !== '')];
    }

    /** @return array{type: string, data: array<string, mixed>} */
    private function blogPreview(DOMXPath $xpath, DOMElement $section): array
    {
        return ['type' => 'blog-preview', 'data' => array_filter([
            'heading' => $this->label($xpath, $section),
            'limit' => $xpath->query('.//div[contains(@class, "divide-y")]//a', $section)?->length ?: 3,
        ], fn ($v) => $v !== '')];
    }

    /**
     * Tools teaser. The live block shows tools from the CMS when there are
     * any, so the cards' text is kept as the block's fallback fields.
     *
     * @return array{type: string, data: array<string, mixed>}
     */
    private function toolsTeaser(DOMXPath $xpath, DOMElement $section): array
    {
        $data = ['label' => $this->label($xpath, $section)];
        $n = 0;

        foreach ($xpath->query('.//div[contains(@class, "border-l-2")]', $section) ?: [] as $card) {
            if (++$n > 2) {
                break;
            }

            $data["tool{$n}_name"] = $this->firstText($xpath, $card, './/h3');
            $data["tool{$n}_body"] = $this->firstText($xpath, $card, './/p');
        }

        return ['type' => 'tools-teaser', 'data' => array_filter($data, fn ($v) => $v !== '')];
    }

    /** @return array{type: string, data: array<string, mixed>} */
    private function cta(DOMXPath $xpath, DOMElement $section): array
    {
        $a = $xpath->query('.//a', $section)?->item(0);

        return ['type' => 'cta', 'data' => array_filter([
            'heading' => $this->firstText($xpath, $section, './/h2'),
            'body' => $this->firstText($xpath, $section, './/p'),
            'cta_label' => $a instanceof DOMElement ? $this->text($a) : '',
            'cta_url' => $a instanceof DOMElement ? $a->getAttribute('href') : '',
        ], fn ($v) => $v !== '')];
    }

    /** @return array<int, string> */
    private function marquee(DOMXPath $xpath, DOMElement $section): array
    {
        $items = [];

        foreach ($xpath->query('.//div[contains(@class, "marquee-track")]/span', $section) ?: [] as $span) {
            // The first text node only; the separator dot is a child span.
            $text = trim((string) preg_replace('/\s+/u', ' ', (string) $span->firstChild?->textContent));

            if ($text !== '' && ! in_array($text, $items, true)) {
                $items[] = $text;
            }
        }

        return $items;
    }

    /** @return array<int, array<string, mixed>> */
    private function caseStudies(string $dist): array
    {
        $summaries = $this->cardSummaries("{$dist}/work/index.html", '/work/');
        $studies = [];

        foreach ($this->listingOrder("{$dist}/work/index.html", '/work/', $dist.'/work') as $index => $slug) {
            [$xpath, $main] = $this->load("{$dist}/work/{$slug}/index.html");

            $stats = [];

            foreach ($xpath->query('.//div[contains(@class, "flex gap-8")]/div', $main) ?: [] as $stat) {
                $stats[$this->firstText($xpath, $stat, './p[1]')] = $this->firstText($xpath, $stat, './p[2]');
            }

            $studies[] = [
                'slug' => $slug,
                'title' => $this->firstText($xpath, $main, './/h1'),
                'category' => $this->firstText($xpath, $main, './/div[contains(@class, "mb-12")]//span[contains(@class, "bg-bg-muted")]'),
                'result' => $this->firstText($xpath, $main, './/h1/following-sibling::p'),
                'summary' => $summaries[$slug] ?? '',
                'duration' => $stats['Duration'] ?? '',
                'tier' => $stats['Engagement'] ?? '',
                'published_at' => $this->derivedDate($index),
                'body' => $this->proseDoc($xpath, $main),
                'seo' => $this->seo($xpath),
            ];
        }

        return $studies;
    }

    /** @return array<int, array<string, mixed>> */
    private function articles(string $dist): array
    {
        $articles = [];

        foreach ($this->listingOrder("{$dist}/article/index.html", '/article/', $dist.'/article') as $index => $slug) {
            [$xpath, $main] = $this->load("{$dist}/article/{$slug}/index.html");

            $articles[] = [
                'slug' => $slug,
                'title' => $this->firstText($xpath, $main, './/h1'),
                'excerpt' => $this->firstText($xpath, $main, './/h1/following-sibling::p'),
                'published_at' => $this->derivedDate($index),
                'body' => $this->proseDoc($xpath, $main),
                'seo' => $this->seo($xpath),
            ];
        }

        return $articles;
    }

    /** @return array<int, array<string, mixed>> */
    private function tools(string $dist): array
    {
        $tools = [];

        foreach ($this->listingOrder("{$dist}/tools/index.html", '/tools/', $dist.'/tools') as $index => $slug) {
            [$xpath, $main] = $this->load("{$dist}/tools/{$slug}/index.html");

            $tools[] = [
                'slug' => $slug,
                'title' => $this->firstText($xpath, $main, './/h1'),
                'description' => $this->firstText($xpath, $main, './/h1/following-sibling::p'),
                'icon' => $this->firstText($xpath, $main, './/span[contains(@class, "text-2xl")]'),
                'category' => $this->firstText($xpath, $main, './/span[contains(@class, "bg-bg-muted")]'),
                'sort_order' => $index + 1,
                'body' => $this->proseDoc($xpath, $main),
                'seo' => $this->seo($xpath),
            ];
        }

        return $tools;
    }

    /** @return array<int, array<string, mixed>> */
    private function resources(string $dist): array
    {
        $resources = [];

        foreach ($this->listingOrder("{$dist}/resources/index.html", '/resources/', $dist.'/resources') as $index => $slug) {
            [$xpath, $main] = $this->load("{$dist}/resources/{$slug}/index.html");

            $resources[] = [
                'slug' => $slug,
                'title' => $this->firstText($xpath, $main, './/h1'),
                'summary' => $this->firstText($xpath, $main, './/h1/following-sibling::p'),
                'sector' => $this->firstText($xpath, $main, './/div[contains(@class, "mb-12")]//span[contains(@class, "bg-bg-muted")]') ?: 'All',
                'sort_order' => $index + 1,
                'description' => $this->proseDoc($xpath, $main),
                'seo' => $this->seo($xpath),
            ];
        }

        return $resources;
    }

    /**
     * Detail slugs in the order the listing shows them, falling back to the
     * directories present for anything the listing does not link.
     *
     * @return array<int, string>
     */
    private function listingOrder(string $listing, string $prefix, string $directory): array
    {
        $slugs = [];

        if (is_file($listing)) {
            [$xpath, $main] = $this->load($listing);

            foreach ($xpath->query('.//a[starts-with(@href, "'.$prefix.'")]', $main) ?: [] as $a) {
                $slug = trim(substr($a->getAttribute('href'), strlen($prefix)), '/');

                if ($slug !== '' && ! str_contains($slug, '/') && ! in_array($slug, $slugs, true)) {
                    $slugs[] = $slug;
                }
            }
        }

        foreach (glob($directory.'/*/index.html') ?: [] as $file) {
            $slug = basename(dirname($file));

            if (! in_array($slug, $slugs, true)) {
                $slugs[] = $slug;
            }
        }

        return array_values(array_filter($slugs, fn (string $slug): bool => is_file("{$directory}/{$slug}/index.html")));
    }

    /** @return array<string, string> slug => summary text on the listing card */
    private function cardSummaries(string $listing, string $prefix): array
    {
        if (! is_file($listing)) {
            return [];
        }

        [$xpath, $main] = $this->load($listing);
        $summaries = [];

        foreach ($xpath->query('.//a[starts-with(@href, "'.$prefix.'")]', $main) ?: [] as $a) {
            $paragraphs = $xpath->query('./p', $a);
            $last = $paragraphs?->item(max(0, ($paragraphs->length ?? 1) - 1));

            if ($last !== null) {
                $summaries[trim(substr($a->getAttribute('href'), strlen($prefix)), '/')] = $this->text($last);
            }
        }

        return $summaries;
    }

    private function derivedDate(int $index): string
    {
        return Carbon::parse('2026-05-18 09:00:00', 'Europe/London')->subWeeks($index)->toIso8601String();
    }

    /** @return array{title: string, description: string} */
    private function seo(DOMXPath $xpath): array
    {
        $description = $xpath->query('//head/meta[@name="description"]')?->item(0);

        return [
            'title' => $this->firstText($xpath, null, '//head/title'),
            'description' => $description instanceof DOMElement ? trim($description->getAttribute('content')) : '',
        ];
    }

    /** @return array<string, mixed>|null */
    private function proseDoc(DOMXPath $xpath, DOMNode $context): ?array
    {
        $prose = $this->find($xpath, $context, 'prose-custom');

        return $prose === null ? null : $this->converter->convert($this->innerHtml($prose));
    }

    /** @return array<string, mixed>|null */
    private function prose(DOMXPath $xpath, DOMNode $context): ?array
    {
        return $this->proseDoc($xpath, $context);
    }

    /** The small uppercase eyebrow above a section heading. */
    private function label(DOMXPath $xpath, DOMElement $section): string
    {
        return $this->firstText($xpath, $section, './/p[contains(@class, "uppercase") and contains(@class, "text-text-tertiary")]');
    }

    /** @return array{0: DOMXPath, 1: DOMElement} */
    private function load(string $file): array
    {
        $document = new DOMDocument;
        @$document->loadHTML('<?xml encoding="UTF-8">'.(string) file_get_contents($file), LIBXML_NOERROR | LIBXML_NOWARNING | LIBXML_NONET);

        $xpath = new DOMXPath($document);
        $main = $xpath->query('//main')?->item(0);

        if (! $main instanceof DOMElement) {
            throw new \RuntimeException("No <main> in {$file}");
        }

        return [$xpath, $main];
    }

    private function find(DOMXPath $xpath, DOMNode $context, string $class): ?DOMElement
    {
        $node = $xpath->query('.//*[contains(concat(" ", normalize-space(@class), " "), " '.$class.' ")]', $context)?->item(0);

        return $node instanceof DOMElement ? $node : null;
    }

    private function hasClass(DOMElement $element, string $class): bool
    {
        return in_array($class, preg_split('/\s+/', $element->getAttribute('class')) ?: [], true);
    }

    private function firstText(DOMXPath $xpath, ?DOMNode $context, string $query): string
    {
        $node = $context === null ? $xpath->query($query)?->item(0) : $xpath->query($query, $context)?->item(0);

        return $node === null ? '' : $this->text($node);
    }

    private function text(DOMNode $node): string
    {
        return trim((string) preg_replace('/\s+/u', ' ', $node->textContent));
    }

    private function innerHtml(DOMElement $element): string
    {
        $html = '';

        foreach ($element->childNodes as $child) {
            $html .= $element->ownerDocument?->saveHTML($child);
        }

        return $html;
    }
}
