<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Promoted collection fields, generated by `php artisan cms:sync-schema`.
 *
 * Generated columns are derived from `data` by Postgres itself, so they
 * cannot drift from the authored value.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            alter table entries
                add column kind text
                generated always as ((data ->> 'kind')) stored
        ");

        DB::statement('
            create index entries_collection_kind_idx
                on entries (collection, kind)
                where deleted_at is null
        ');

        DB::statement("
            alter table entries
                add column featured boolean
                generated always as ((data ->> 'featured')::boolean) stored
        ");

        DB::statement('
            create index entries_collection_featured_idx
                on entries (collection, featured)
                where deleted_at is null
        ');
    }

    public function down(): void
    {
        DB::statement('drop index if exists entries_collection_kind_idx');
        DB::statement('alter table entries drop column if exists kind');
        DB::statement('drop index if exists entries_collection_featured_idx');
        DB::statement('alter table entries drop column if exists featured');
    }
};
