<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Promoted collection fields, generated by `php artisan cms:sync-schema`.
 *
 * Generated columns are derived from `data` by Postgres itself, so they
 * cannot drift from the authored value.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement("
            alter table entries
                add column category text
                generated always as ((data ->> 'category')) stored
        ");

        DB::statement('
            create index entries_collection_category_idx
                on entries (collection, category)
                where deleted_at is null
        ');

        DB::statement("
            alter table entries
                add column sector text
                generated always as ((data ->> 'sector')) stored
        ");

        DB::statement('
            create index entries_collection_sector_idx
                on entries (collection, sector)
                where deleted_at is null
        ');

        DB::statement("
            alter table entries
                add column tier text
                generated always as ((data ->> 'tier')) stored
        ");

        DB::statement('
            create index entries_collection_tier_idx
                on entries (collection, tier)
                where deleted_at is null
        ');

        DB::statement("
            alter table entries
                add column funnel_stage text
                generated always as ((data ->> 'funnel_stage')) stored
        ");

        DB::statement('
            create index entries_collection_funnel_stage_idx
                on entries (collection, funnel_stage)
                where deleted_at is null
        ');
    }

    public function down(): void
    {
        DB::statement('drop index if exists entries_collection_category_idx');
        DB::statement('alter table entries drop column if exists category');
        DB::statement('drop index if exists entries_collection_sector_idx');
        DB::statement('alter table entries drop column if exists sector');
        DB::statement('drop index if exists entries_collection_tier_idx');
        DB::statement('alter table entries drop column if exists tier');
        DB::statement('drop index if exists entries_collection_funnel_stage_idx');
        DB::statement('alter table entries drop column if exists funnel_stage');
    }
};
